merge from the main trunk

diff --git a/branches/restructure/edu.rice.cs.hpc.traceviewer/scripts/install b/branches/restructure/edu.rice.cs.hpc.traceviewer/scripts/install
--- a/branches/restructure/edu.rice.cs.hpc.traceviewer/scripts/install
+++ b/branches/restructure/edu.rice.cs.hpc.traceviewer/scripts/install
@@ -1,15 +1,27 @@
 #!/bin/sh
 #
-# Install hpctraceviewer into hpctoolkit directory.
+# Copyright (c) 2002-2012, Rice University.
+# See the file README.License for details.
 #
-# Usage: ./install dir
+# Install hpcviewer into hpctoolkit directory.
+# This script is only for Unix and X windows.
 #
-# where "dir" is the top-level hpctoolkit install directory, the same
-# directory specified as --prefix in hpctoolkit's configure.  Run this
-# script in its own directory, as ./install.
+# Usage: ./install [-j java-dir] install-dir
 #
-# $Id: install 327 2009-04-22 19:15:51Z krentel $
+# where 'java-dir' is a Java jdk or jre directory,
+# and 'install-dir' is the directory in which to install.
 #
+# Run this script from its own directory as ./install.
+#
+# $Id$
+#
+
+name=hpctraceviewer
+install_subdirs='configuration plugins'
+
+#------------------------------------------------------------
+# Error messages
+#------------------------------------------------------------
 
 die()
 {
@@ -20,65 +32,116 @@ die()
 usage()
 {
     cat <<EOF
-Usage: $0 hpctoolkit-prefix-directory
+Usage: ./install [-j java-dir] install-dir
+
+where 'java-dir' is a Java jdk or jre directory,
+and 'install-dir' is the directory in which to install.
+
+Run this script from its own directory as ./install.
 EOF
     exit 0
 }
 
-#
-# See if the directory ($1) looks like an hpctoolkit install
-# directory.
-#
-hpctk_dir="$1"
-test "x$hpctk_dir" != x || usage
+#------------------------------------------------------------
+# Command-Line Options
+#------------------------------------------------------------
 
-if test -x "${hpctk_dir}/bin/hpcrun" -o -x "${hpctk_dir}/bin/hpclink" \
-    && test -d "${hpctk_dir}/libexec/hpctoolkit"
-then :
-else
-    cat <<EOF
+java_dir=
+install_dir=
 
-Warning: possible bad directory: $hpctk_dir
-
-This directory does not look like an hpctoolkit install directory.
-Either the directory does not exist, or hpctoolkit is not installed
-there.  This is not necessarily fatal, but it is suspicious and you
-should double check the directory.
-
-EOF
-    echo -n "Continue with the install? [ny] "
-    read ans
-    case "$ans" in
-	[yY]* ) ;;
-	* ) exit 1 ;;
+while test -n "$1"
+do
+    arg="$1" ; shift
+    case "$arg" in
+	-h | -help | --help )
+	    usage
+	    ;;
+	-j | -java | --java )
+	    test "x$1" != x || die "missing directory for $arg"
+	    java_dir="$1"
+	    shift
+	    ;;
+	-* )
+	    die "unknown option: $arg"
+	    ;;
+	* )
+	    install_dir="$arg"
+	    break
+	    ;;
     esac
+done
+
+test "x$install_dir" != x || usage
+
+#------------------------------------------------------------
+# Java tests
+#------------------------------------------------------------
+
+# Java_dir is the jdk or jre directory, if specified.
+
+java_bindir=
+if test -n "$java_dir" ; then
+    if test -f "${java_dir}/bin/java" ; then
+	java_bindir="${java_dir}/bin"
+    elif test -f "${java_dir}/java" ; then
+	java_bindir="${java_dir}"
+    else
+	die "unable to find java in: $java_dir"
+    fi
+    PATH="${java_bindir}:$PATH"
 fi
 
-#
-# Install hpctraceviewer.sh into bin (as hpctraceviewer), other files into
-# libexec, and reset permissions.
-#
-bin_dir="${hpctk_dir}/bin"
-libexec_dir="${hpctk_dir}/libexec/hpctraceviewer"
+# Check that version is 1.5 or later.
+
+java_version=`java -version 2>&1 | grep -i java | grep -i vers | head -1`
+if test "x$java_version" = x ; then
+    die "unable to find program 'java' on your PATH"
+fi
+minor=`expr "$java_version" : '[^.]*\.\([0-9]*\)'`
+test "$minor" -ge 5 >/dev/null 2>&1
+if test $? -ne 0 ; then
+    die "$java_version is too old, use Java 1.5 or later"
+fi
+
+#------------------------------------------------------------
+# Install the viewer and reset permissions.
+#------------------------------------------------------------
+
+bin_dir="${install_dir}/bin"
+libexec_dir="${install_dir}/libexec/$name"
+binary_file="$name"
+ini_file="${name}.ini"
+sh_file="${name}.sh"
 
 mkdir -p "$bin_dir" "$libexec_dir" \
     || die "unable to mkdir install directories"
 
-cp -f hpctraceviewer.sh "${bin_dir}/hpctraceviewer" \
-    || die "unable to install bin/hpctraceviewer"
+cp -f "$sh_file" "${bin_dir}/$name" \
+    || die "unable to install bin files"
 
-cp -f hpctraceviewer hpctraceviewer.ini "$libexec_dir" \
+cp -f "$binary_file" "$ini_file" "$libexec_dir" \
     || die "unable to install libexec files"
 
-tar cf - configuration plugins | ( cd "$libexec_dir" && tar xvf - )
+if test -n "$java_bindir" ; then
+    orig="${bin_dir}/${name}"
+    tmp="${bin_dir}/${name}.tmp"
+    rm -f "$tmp"
+    mv -f "$orig" "$tmp"
+    sed -e "s,^#.*JAVA_BINDIR=.*\$,JAVA_BINDIR='${java_bindir}'," \
+	<"$tmp"  >"$orig"
+    rm -f "$tmp"
+fi
+
+tar cf - $install_subdirs | ( cd "$libexec_dir" && tar xvf - )
 test $? -eq 0 || die "unable to install libexec files"
 
+# Note: the find idiom below is used to handle file names with
+# embedded spaces.
+
 echo "Resetting permissions ..."
-chmod 755 "${bin_dir}/hpctraceviewer" "${libexec_dir}/hpctraceviewer"
+chmod a+rx "${bin_dir}/$name" "${libexec_dir}/$binary_file"
+find "$libexec_dir" -type d -exec chmod a+rx {} \;
+find "$libexec_dir" -type f -exec chmod a+r  {} \;
 
-# NOTE: the find idiom below is used to deftly handle file names with embedded spaces 
-find "$libexec_dir" -type d -exec chmod 755 {} \;
-find "$libexec_dir" -type f -exec chmod a+r {} \;
-
-echo "hpctraceviewer install done"
+echo "done"
 exit 0
